const mongoose = require("mongoose");
const userId = new mongoose.Types.ObjectId("69a19808d52fba794265de4a");

const userData = [
  {
    firstName: "Harshal",
    lastName: "Waghmare",
    email: "tradeflowAdmin@gmail.com",
    password: "admin@123",
    isVerified: true,
  },
];

const holdingsData = [
  {
    user: userId,
    instrument: "ALEMBICLTD",
    quantity: 2,
    avgCost: 66.65,
    ltp: 70.0,
    prevClose: 70.4,
  },
  {
    user: userId,
    instrument: "BHEL",
    quantity: 43,
    avgCost: 64.93,
    ltp: 82.3,
    prevClose: 81.56,
  },
  {
    user: userId,
    instrument: "GAIL",
    quantity: 16,
    avgCost: 98.17,
    ltp: 110.0,
    prevClose: 111.7,
  },
  {
    user: userId,
    instrument: "IDEA",
    quantity: 11,
    avgCost: 6.98,
    ltp: 7.07,
    prevClose: 7.35,
  },
  {
    user: userId,
    instrument: "IDFC",
    quantity: 11,
    avgCost: 80.25,
    ltp: 91.22,
    prevClose: 91.5,
  },
  {
    user: userId,
    instrument: "IDFCFIRSTB",
    quantity: 10,
    avgCost: 55.6,
    ltp: 66.95,
    prevClose: 67.4,
  },
  {
    user: userId,
    instrument: "IOC",
    quantity: 20,
    avgCost: 82.3,
    ltp: 87.55,
    prevClose: 87.0,
  },
  {
    user: userId,
    instrument: "IRFC",
    quantity: 6,
    avgCost: 29.23,
    ltp: 33.98,
    prevClose: 33.56,
  },
  {
    user: userId,
    instrument: "KTKBANK",
    quantity: 8,
    avgCost: 75.32,
    ltp: 130.55,
    prevClose: 128.65,
  },
  {
    user: userId,
    instrument: "PNB",
    quantity: 35,
    avgCost: 36.24,
    ltp: 49.33,
    prevClose: 48.99,
  },
  {
    user: userId,
    instrument: "RVNL",
    quantity: 4,
    avgCost: 71.9,
    ltp: 121.9,
    prevClose: 118.75,
  },
  {
    user: userId,
    instrument: "SAIL",
    quantity: 2,
    avgCost: 87.0,
    ltp: 82.8,
    prevClose: 84.05,
  },
  {
    user: userId,
    instrument: "SBIN",
    quantity: 4,
    avgCost: 541.76,
    ltp: 586.3,
    prevClose: 586.3,
  },
  {
    user: userId,
    instrument: "SUZLON",
    quantity: 1,
    avgCost: 7.95,
    ltp: 8.64,
    prevClose: 8.22,
  },
  {
    user: userId,
    instrument: "TATASTEEL",
    quantity: 3,
    avgCost: 116.22,
    ltp: 106.0,
    prevClose: 107.4,
  },
  {
    user: userId,
    instrument: "UCOBANK",
    quantity: 5,
    avgCost: 28.55,
    ltp: 27.15,
    prevClose: 27.17,
  },
  {
    user: userId,
    instrument: "WIPRO",
    quantity: 1,
    avgCost: 396.9,
    ltp: 382.5,
    prevClose: 386.8,
  },
];

const positionsData = [
  {
    user: userId,
    product: "NRML",
    instrument: "USDINR 23JUN FUT",
    exchange: "CDS",
    quantity: 1,
    avgPrice: 82.0375,
    ltp: 82.5275,
  },
  {
    user: userId,
    product: "NRML",
    instrument: "USDINR 23MAY FUT",
    exchange: "CDS",
    quantity: 1,
    avgPrice: 82.1625,
    ltp: 82.4225,
  },
  {
    user: userId,
    product: "NRML",
    instrument: "GOLDPETAL 23MAY FUT",
    exchange: "MCX",
    quantity: 1,
    avgPrice: 6134.0,
    ltp: 6059.0,
  },
  {
    user: userId,
    product: "NRML",
    instrument: "11TH W 23MAY 18700 CE",
    exchange: "NSE",
    quantity: 50,
    avgPrice: 1.65,
    ltp: 1.65,
  },
  {
    user: userId,
    product: "NRML",
    instrument: "11TH W 23MAY 18750 CE",
    exchange: "NSE",
    quantity: 50,
    avgPrice: 1.45,
    ltp: 1.2,
  },
  {
    user: userId,
    product: "CNC",
    instrument: "IDFCFIRSTB",
    exchange: "NSE",
    quantity: 1,
    avgPrice: 64.7,
    ltp: 66.95,
  },
];

const bidsData = [
  {
    user: userId,
    instrument: "HINDCOPPER",
    eligibleQty: 1,
    lastPrice: 102.65,
    holdingPrice: 131.7,
    auctionNo: "#2531",
  },
  {
    user: userId,
    instrument: "HUDCO",
    eligibleQty: 1,
    lastPrice: 57.7,
    holdingPrice: 41.35,
    auctionNo: "#2532",
  },
  {
    user: userId,
    instrument: "IOC",
    eligibleQty: 5,
    lastPrice: 87.55,
    holdingPrice: 55.04,
    auctionNo: "#2539",
  },
  {
    user: userId,
    instrument: "IRCON",
    eligibleQty: 1,
    lastPrice: 80.8,
    holdingPrice: 46.1,
    auctionNo: "#2540",
  },
  {
    user: userId,
    instrument: "JPPOWER",
    eligibleQty: 6,
    lastPrice: 0,
    holdingPrice: 7.45,
    auctionNo: "#5003",
  },
  {
    user: userId,
    instrument: "L&TFH",
    eligibleQty: 2,
    lastPrice: 99.9,
    holdingPrice: 90.92,
    auctionNo: "#5013",
  },
  {
    user: userId,
    instrument: "NCC",
    eligibleQty: 1,
    lastPrice: 113.25,
    holdingPrice: 70.2,
    auctionNo: "#5033",
  },
  {
    user: userId,
    instrument: "NIACL",
    eligibleQty: 1,
    lastPrice: 119.45,
    holdingPrice: 138.25,
    auctionNo: "#5035",
  },
  {
    user: userId,
    instrument: "PNB",
    eligibleQty: 26,
    lastPrice: 49.3,
    holdingPrice: 37.96,
    auctionNo: "#5046",
  },
  {
    user: userId,
    instrument: "RCF",
    eligibleQty: 1,
    lastPrice: 107.15,
    holdingPrice: 102.15,
    auctionNo: "#7504",
  },
  {
    user: userId,
    instrument: "REDINGTON",
    eligibleQty: 1,
    lastPrice: 173.45,
    holdingPrice: 145.4,
    auctionNo: "#7505",
  },
  {
    user: userId,
    instrument: "RVNL",
    eligibleQty: 6,
    lastPrice: 121.85,
    holdingPrice: 69.83,
    auctionNo: "#7510",
  },
  {
    user: userId,
    instrument: "SBIN",
    eligibleQty: 13,
    lastPrice: 586.3,
    holdingPrice: 555.1,
    auctionNo: "#7518",
  },
  {
    user: userId,
    instrument: "SJVN",
    eligibleQty: 1,
    lastPrice: 37.0,
    holdingPrice: 30.45,
    auctionNo: "#7521",
  },
  {
    user: userId,
    instrument: "TATAMOTORS",
    eligibleQty: 1,
    lastPrice: 515.5,
    holdingPrice: 470.0,
    auctionNo: "#7529",
  },
  {
    user: userId,
    instrument: "UCOBANK",
    eligibleQty: 1,
    lastPrice: 27.2,
    holdingPrice: 13.25,
    auctionNo: "#7536",
  },
  {
    user: userId,
    instrument: "WIPRO",
    eligibleQty: 6,
    lastPrice: 382.3,
    holdingPrice: 377.17,
    auctionNo: "#7544",
  },
  {
    user: userId,
    instrument: "ZOMATO",
    eligibleQty: 1,
    lastPrice: 63.35,
    holdingPrice: 140.0,
    auctionNo: "#7547",
  },
];

const ordersData = [
  {
    user: userId,
    type: "SELL",
    instrument: "PNB",
    exchange: "NSE",
    product: "MIS",
    quantity: 1,
    ltp: 49.3,
    price: 48.5,
    status: "OPEN",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "INFY",
    exchange: "NSE",
    product: "MIS",
    quantity: 1,
    ltp: 49.3,
    price: 49.5,
    status: "OPEN",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "USDINR 23MAY FUT",
    exchange: "CDS",
    product: "NRML",
    quantity: 3,
    ltp: 82.4225,
    price: 81.0,
    status: "OPEN",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "USDINR 23MAY FUT",
    exchange: "CDS",
    product: "MIS",
    quantity: 1,
    ltp: 82.4225,
    price: 81.0,
    status: "OPEN",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "SBIN",
    exchange: "BSE",
    product: "MIS",
    quantity: 1,
    ltp: 586.5,
    price: 585.0,
    status: "OPEN",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "VEDL",
    exchange: "NSE",
    product: "CNC",
    quantity: 1,
    ltp: 279.45,
    price: 290.0,
    status: "OPEN",
  },

  {
    user: userId,
    type: "BUY",
    instrument: "11TH W 23MAY 18300 CE",
    exchange: "NSE",
    product: "MIS",
    quantity: 50,
    ltp: 0,
    price: 0,
    status: "REJECTED",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "11TH W 23MAY 18300 CE",
    exchange: "NSE",
    product: "NRML",
    quantity: 50,
    ltp: 0,
    price: 0,
    status: "REJECTED",
  },
  {
    user: userId,
    type: "SELL",
    instrument: "PNB",
    exchange: "NSE",
    product: "CNC",
    quantity: 1,
    ltp: 51.2,
    price: 51.2,
    status: "CANCELLED",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "INFY",
    exchange: "NSE",
    product: "CNC",
    quantity: 1,
    ltp: 50.75,
    price: 50.75,
    status: "COMPLETE",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "VEDL",
    exchange: "NSE",
    product: "MIS",
    quantity: 1,
    ltp: 283.4,
    price: 283.4,
    status: "COMPLETE",
  },

  {
    user: userId,
    type: "SELL",
    instrument: "PNB",
    exchange: "NSE",
    product: "CNC",
    quantity: 1,
    ltp: 50.4,
    price: 50.4,
    status: "COMPLETE",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "PNB",
    exchange: "NSE",
    product: "CNC",
    quantity: 1,
    ltp: 50.75,
    price: 50.75,
    status: "COMPLETE",
  },
  {
    user: userId,
    type: "BUY",
    instrument: "VEDL",
    exchange: "NSE",
    product: "MIS",
    quantity: 1,
    ltp: 283.4,
    price: 283.4,
    status: "COMPLETE",
  },
  {
    user: userId,
    type: "SELL",
    instrument: "VEDL",
    exchange: "NSE",
    product: "MIS",
    quantity: 1,
    ltp: 283.4,
    price: 283.4,
    status: "COMPLETE",
  },
];

const fundsData = [
  {
    user: userId,
    equity: {
      openingBalance: 100000.0,
      availableCash: 100000.0,
      payin: 0.0,
      payout: 0.0,
      spanMargin: 0.0,
      deliveryMargin: 0.0,
      exposure: 0.0,
      optionsPremium: 0.0,
      collateralLiquidFunds: 0.0,
      collateralEquity: 0.0,
    },
    commodity: {
      openingBalance: 50000.0,
      availableCash: 50000.0,
      payin: 0.0,
      payout: 0.0,
      spanMargin: 0.0,
      deliveryMargin: 0.0,
      exposure: 0.0,
      optionsPremium: 0.0,
      collateralLiquidFunds: 0.0,
      collateralEquity: 0.0,
    },
  },
];

module.exports = {
  userdata: userData,
  holdingsdata: holdingsData,
  positionsdata: positionsData,
  bidsdata: bidsData,
  ordersdata: ordersData,
  fundsdata: fundsData,
};
